---
- name: Sample playbook
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check connectivity
      ping:
    - name: Print hostname
      debug:
        msg: "Host is {{ inventory_hostname }}" 
